export const USER_REGISTER_PENDING="USER_REGISTER_PENDING"
export const USER_LOGIN_PENDING="USER_LOGIN_PENDING"
export const GET_USER_PENDING="GET_USER_PENDING"
export const USER='USER'
export const USER_LOGOUT="USER_LOGOUT"